/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package sistemagerenciamentoclientes.view;
import com.sun.jdi.connect.spi.Connection;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import sistemagerenciamentoclientes.model.Clientes;
import sistemagerenciamentoclientes.repository.ClienteRepository;




/**
 *
 * @author joser
 */
public class PesquisaDeCliente extends javax.swing.JInternalFrame {
    private static PesquisaDeCliente instancia;
    private TelaAlteracaoClientes telaAlteracaoClientes;
    private TelaInicial telaInicial;

    /**
     * Creates new form PesquisaDeCliente
     */
    public PesquisaDeCliente(TelaInicial telaInicial) {
        initComponents();
        this.telaInicial = telaInicial; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtPesquisa = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JToggleButton();
        btnFechar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        setTitle("Alteração de Cadastro");
        setVisible(true);

        jLabel1.setText("Para alterar os dados de um usuário, insira o CPF para realizar a busca:");

        txtPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisaActionPerformed(evt);
            }
        });

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPesquisar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(btnFechar)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar))
                .addGap(18, 18, 18)
                .addComponent(btnFechar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisaActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
   // Recupera o CPF inserido no campo de pesquisa
    String cpf = txtPesquisa.getText();
    System.out.println("CPF inserido: " + cpf);  // Verifica o CPF no console

    if (cpf.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, insira um CPF para realizar a pesquisa.", 
                                      "Aviso", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Cria uma instância do ClientesRepository para realizar a consulta
    ClienteRepository clienteRepository = new ClienteRepository();
    Clientes cliente = clienteRepository.selecionar(cpf);  // Método para buscar diretamente no repositório

    if (cliente != null) {
        
        // Se o cliente for encontrado, abre a tela de alterar os dados
        try {
            // Cria uma instância da tela de alteração de clientes
            telaAlteracaoClientes = TelaAlteracaoClientes.getInstancia(telaInicial);
            telaAlteracaoClientes.setCliente(cliente);

            // Recupera o JDesktopPane da tela inicial
            JDesktopPane desktopPane = telaInicial.getDesktopPane();  // Método para obter o JDesktopPane de TelaInicial

            // Verifica se a tela já está adicionada ao JDesktopPane
            if (!desktopPane.isAncestorOf(telaAlteracaoClientes)) {
                desktopPane.add(telaAlteracaoClientes);  // Adiciona a tela diretamente
                telaAlteracaoClientes.setDefaultCloseOperation(JInternalFrame.DO_NOTHING_ON_CLOSE);
            }

            // Tenta selecionar a tela
            telaAlteracaoClientes.setSelected(true);
            telaAlteracaoClientes.setVisible(true);
        } catch (Exception ex) {
            // Em caso de erro, mostra uma mensagem de erro
            JOptionPane.showMessageDialog(null, 
                    "Erro ao abrir a tela de alteração de clientes: " + ex.getMessage(),
                    "Pesquisa de clientes",
                    JOptionPane.ERROR_MESSAGE);
        }
        
    } else {
        // Se não encontrar o cliente, exibe uma mensagem de erro
        JOptionPane.showMessageDialog(this, "Cliente não encontrado com o CPF: " + cpf, 
                                      "Erro", JOptionPane.ERROR_MESSAGE);
    }
    
    fecharJanela(); //Após a janela de alteração ser aberta, a de pesquisa é fechada atrás
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        // TODO add your handling code here:
        fecharJanela();
    }//GEN-LAST:event_btnFecharActionPerformed
    
        //função para fechar a janela
    private void fecharJanela(){
        instancia = null;
        dispose();
    }
    
    public static PesquisaDeCliente getInstancia(TelaInicial telaInicial) {
    if (instancia == null)
        instancia = new PesquisaDeCliente(telaInicial);
    return instancia;
}
    
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFechar;
    private javax.swing.JToggleButton btnPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables
}
